all: abcd
abcd: abcd.c
	gcc -std=c99 abcd.c -falign-functions=4096 -o abcd

auto: auto.c
	gcc -std=c99 auto.c -falign-functions=4096 -o auto

linear: linear.c
	gcc -std=c99 linear.c -falign-functions=4096 -o linear
